### ISSUE TITLE
conversion from navd88 to xgeoid20b for schism hgrid

### ISSUE THREAD

**Issue by feiye-vims** [oceanmodeling/coastalmodeling-vdatum#1]
It seems there might be an issue with the sign of the z. SCHISM's hgrid's z is positive downward, like the "sounding" in vdatum.

The following example is from a SCHISM hgrid on NAVD88, showing the first node:
1 -94.21610700 29.75730400 -2.01908093

Vdatum gives -1.950 after transformed to xgeoid20b:
![image](https://github.com/user-attachments/assets/9b82bfe4-4418-442d-add4-aa8915b08fd5)

But cmvd gives -2.075, from the script:
```python
from coastalmodeling_vdatum import vdatum, _path
from pylib import schism_grid

PATH = '/sciclone/schism10/Hgrid_projects/GEOTIFFs/'

_path.NAVD88_G2018=f"{PATH}/us_noaa_g2018u0.tif"
_path.XGEOID20B=f"{PATH}/xGEOID20B.tif"
_path.MLLW_ITRF2020_2020=f"{PATH}/us_noaa_nos_MLLW-ITRF2020_2020.0_nwldatum_4.7.0_20240621_.tif"
_path.LMSL_ITRF2020_2020=f"{PATH}/us_noaa_nos_LMSL-ITRF2020_2020.0_nwldatum_4.7.0_20240621_.tif"

gd = schism_grid('/sciclone/schism10/feiye/STOFS3D-v8/I09/hgrid.gr3')
x,y,z = vdatum.convert("navd88", "xgeoid20b", gd.y, gd.x, gd.z, online=False, epoch=None)
```

It seems the difference is close, just the sign of the difference is opposite.

**Comment by feiye-vims** [comment]
I looked at more points, it seems the amount of difference varies, so it may not be the sign.

Maybe we should not expect vdatum and cmvd to be the same?

**Comment by felicio93** [comment]
@feiye-vims, the amount of difference varies (from what I have seen in a few millimeters to a few centimeters), and it won't match vdatum perfectly (maybe due to differences in the interpolation  used by vdatum and what is used in proj/pyproj, different pipelines, files etc). Honestly vdatum is a bit of a blackbox to me, so I don't really know the details of what is happening behind the scenes there.

 It is a good test to compare what the package does and vdatum for multiple points. So far I have only looked at a few points for sanity check. If you can share what you find that would be great!

**Comment by feiye-vims** [comment]
Sounds good, I can plot the difference on a 2D grid and see the pattern of the difference, probably after I come back from AGU next week.

**Comment by felicio93** [comment]
I am trying to replicate your problem and this is what I get:
From cmvd:
![image](https://github.com/user-attachments/assets/0c3724fe-8e1b-4a4a-9513-c9a7e7157d0f)

from vdatum:
![image](https://github.com/user-attachments/assets/4fc3f694-e73d-4665-81e1-6e6d170f726c)

The difference between the two is a little over 1.5cm, correct?

**Comment by feiye-vims** [comment]
I used "sounding" since hgrid's z is positive down.

**Comment by feiye-vims** [comment]
It seems different versions of vdatum also give different results. I see the latest vdatum has more regions than before.

**Comment by felicio93** [comment]
I see, maybe the easy solution here is to multiply the mesh values by -1 before using cmvd, and then multiply it back once the conversion is done? like:

**Comment by feiye-vims** [comment]
> I see, maybe the easy solution here is to multiply the mesh values by -1 before using cmvd, and then multiply it back once the conversion is done? like: ![image](https://private-user-images.githubusercontent.com/61760479/392578591-9056ab6d-0609-49fc-92d9-7832ec99b218.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNDk1MTcsIm5iZiI6MTczMzM0OTIxNywicGF0aCI6Ii82MTc2MDQ3OS8zOTI1Nzg1OTEtOTA1NmFiNmQtMDYwOS00OWZjLTkyZDktNzgzMmVjOTliMjE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDIxNTMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlNmIwYzBiNWU4NzhkZjE0OTcwYjZjMTkwZTk2YzQ4NTA4MjQzYmE3OGE2MmRkYjZjZDU4M2NhMGY1OTM4OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BpBqR0FRp3ShfGFnbKkfHIBOqGpCQ-nOkUwcm_3YsSo)

Sure, so you mean the parameter "z" in vdatum.convert() should be positive upward?

**Comment by felicio93** [comment]
Yes!

**Comment by feiye-vims** [comment]
> Yes!

Sounds good, then you may want to also change the example you showed in README.

**Comment by felicio93** [comment]
Ok, example changed! Please let me know if everything works and if I can close the issue.
