### ISSUE TITLE
Minor comments

### ISSUE THREAD

**Issue by feiye-vims** [oceanmodeling/coastalmodeling-vdatum#2]
I like the package very much, which makes our datum conversion much simpler.

Some minor comments:
In the README, there is a "=" missing under "Compute Node (offline) Applications"

In the README, it probably helps if you mention the available datums "xgeoid20b","navd88","mllw","lmsl", or direct users to the docstring of "def convert()"

I put "NAVD88_G2018" first, which returns an error with undefined g_d, because convert() failed. It may be more informative to throw an exception saying the user provide datum is not supported.

Thanks!

**Comment by felicio93** [comment]
Thanks @feiye-vims, I really appreciate your comments!
I updated the README with the "="

The docstring of "def convert()" already mentioned the vdatum available (see the "Parameters" section). But I also added to the the beginning of the docstring to make sure that is the first things the user sees. 

You are right, the exception is a good idea. I added a check at the convert function for that.
